### PR TITLE
Allow to anonymize input from stdin

### LINKED ISSUE #7: program crashes if no file found
program crashes if it does not find the file it should anonymize

### PR DESCRIPTION
**Pull request by gsantner**
This PR adds the ability to read contents from standard input, thus allowing easy piping into slfa. I also updated to docs to mention this ability, and what it can be used for example.

I also created a conf folder which contains the existing embededdipv4 config, and a conf having ipv4,6,embedded, so not every user needs to write the most common conf self.

This opens a lot of new ways of using slfa while not blowing up slfa with a lot of pack/unpack libraries.

This PR also fixes #7, it prints the not found file now, and exits with code 1 afterwards.

Note: As the previous PR, I tried to keep low with amount of changes, so it is easy to review. (Saw many things that could be improved :) )

### CODE REVIEW

**Comment by jgerhards** [comment]
Thanks for the PR. Any suggestions are welcome :)

**Comment by gsantner** [comment]
Thanks for fast response!
Are you active on some IRC server or like that where I could ask some questions? :D

Especially I would like to refactor the structure and buildfiles so it is open-able with IDEs. Currently this is not easily possible, and thus not very welcome to new contributors - who want maybe to start contributing to slfa. This won't change any functionalty of slfa itself, but the things around it. Most part is renaming, moving and refactoring (to be honest, code quality isn't very good at current state).

**Comment by jgerhards** [comment]
I'm currently working on another big project, so I don't have as much time, but if you could send me an E-Mail that'd be great. An issue tracker might also work, since other people can see it as well.

**Comment by gsantner** [comment]
Basically the said above is something I can do for this project.

**Comment by jgerhards** [comment]
I'd be glad if you could do that (i with you on the quality of the current code ;))! I also plan on trying to add module tests to the builds when i am finished with my current project.
However, I'm a bit confused on the IDE part - i can open the project using eclipse (however, i might overlook something, haven't worked that much with java and its IDEs jet).

**Comment by gsantner** [comment]
Currently there are some autogenerated files in the repo (not needed files that may create conflicts) and it's not easy to get slfa working of the box with intelliJ. 

I did the first steps to fix this in <https://github.com/gsantner/SLFA/commits/master>, and will continue with auto-reformatting. As said that PR won't have any functionality change.

**Pull request merged**
