### PR TITLE
Reformat, organize, fix path bugs, support eclipse and intelliJ

### PR DESCRIPTION
**Pull request by gsantner**
* Move packages and rename classes slightly
* Auto-reformat all sources
* Remove autogenerated build files
* Update buildscript
* Update tests to not fail on different working directory

### CODE REVIEW

**Comment by gsantner** [comment]
@jgerhards Don't be afraid of the amount of changes, the most stuff is whitespace changes, removing autogenerated files. Source code/logic itself is not modified.

**Comment by gsantner** [comment]
@jgerhards Don't be afraid of the amount of changes, the most stuff is whitespace changes, removing autogenerated files. Source code/logic itself is not modified.

After this gets merged I can start on improving the code :smiley:

**Comment by gsantner** [comment]
While looking at file structure I found out, that the project doesn't have any LICENSE file, and doesn't specify. I don't know what/which do you prefer, but I think you should add one

**Comment by jgerhards** [comment]
I will get back to the PR asap, however, my virtual machine crashed and i have to learn for an exam coming up, so I don't have as much time currently. Will try to get back to it on the weekend. I will include a LICENSE file when i have time aswell, for the time being it is the ASL2.0.

**Comment by jgerhards** [comment]
Managed to get my VM to work again to look over it. Thanks for the PR, looking forward to further contributions.

**Pull request merged**
